### ISSUE TITLE
Hardware-Check page needs revision

### ISSUE THREAD

**Issue by besselfunct** [ferrous-systems/espressif-trainings#94]
[02_1_hardware.md](https://github.com/ferrous-systems/espressif-trainings/blob/main/book/src/02_1_hardware.md) is inconsistent and a bit confusing.
I purchased the Rust development board from Mouser, which:
1. Does not have a UART bridge on the board
2. Does not show up where the Windows and Linux instructions say it should
_However_, it _does_ show up where the MacOS instructions say it should, with the vendor ID and product ID given.

In this instance I can understand why it would be undesirable to present the learner with a minimum of options, but I think that it would be better to provide a clear fork showing the expected behavior for the ESP32-C3-DevKitC-02 and the ESP32-C3-DevKit-RUST-1. I also think pictures might be helpful. I can provide an image of both boards, unless image integration is frowned on in this work.

**Comment by Dajamante** [comment]
Hi @besselfunct (I see you have more space missions on your uniform than I 🤣)
The instructions for Linux should have been solved by #101 - UART was replace by USB.

For your other comments, we image and block diagram in  #102
